name: Backend CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: ${{ secrets.MYSQL_HOST_PORT }}
          container port: ${{ secrets.MYSQL_CONTAINER_PORT }}
          mysql version: ${{ secrets.MYSQL_VERSION }}
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}
      - name: Setup db config profile
        working-directory: /backend/src/main/resources
        run: echo "${{ secrets.APPLICATION_DB_YAML }}" > application-db.yml
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Test with Gradle Wrapper
        working-directory: /backend
        run: ./gradlew test
