name: Frontend CD

on:
  push:
    branches:
      - main
      - dev/fe

jobs:
  build:
    runs-on: self-hosted
    env:
      frontend-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create environment file
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > ${{ env.frontend-directory }}/.env.production
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> ${{ env.frontend-directory }}/.env.production
          else
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_BETA_API_URL }}" > ${{ env.frontend-directory }}/.env.development
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BETA_BASE_URL }}" >> ${{ env.frontend-directory }}/.env.development
          fi

          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ${{ env.frontend-directory }}/.env.production
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> ${{ env.frontend-directory }}/.env.production
          echo "SENTRY_DSN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ${{ env.frontend-directory }}/.env.sentry-build-plugin

     - name: Set environment file permissions
        run: chmod 644 ${{ env.frontend-directory }}/.env.*

      - name: Set Sentry environment file permissions
        run: chmod 644 ${{ env.frontend-directory }}/.env.sentry-build-plugin

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.frontend-directory }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ env.frontend-directory }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-zap-front
          path: ${{ env.frontend-directory }}/dist/**

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Make Artifact Directory
        run: mkdir ${{ secrets.FRONT_DIRECTORY }}
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-zap-front
          path: ${{ secrets.FRONT_DIRECTORY }}
      - name: Move To S3
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            aws s3 cp --recursive ${{ secrets.FRONT_DIRECTORY }} s3://techcourse-project-2024/code-zap
          else
            aws s3 cp --recursive ${{ secrets.FRONT_DIRECTORY }} s3://techcourse-project-2024/code-zap-staging
          fi
          rm -rf ${{ secrets.FRONT_DIRECTORY }}
